baseURL = "https://nchesnaye.github.io/photography/" # Keep this simple in source config
languageCode = 'en-us'
title = 'Nick Chesnaye Photography'
[params]
  description = "Amsterdam-based photographer available for events / weddings / portraits"
